language: objective-c
osx_image: xcode8.3
script:
- xcodebuild -project DurationReporter.xcodeproj -scheme DurationReporter -sdk iphonesimulator -destination 'platform=iOS Simulator,name=iPhone 6,OS=10.3' test

